### Register
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "name": "Kasumi",
    "email": "kasummi@gmail.com",
    "password": "kasumigaoka",
    "identity_type": "Paspor",
    "identity_number": "2234452",
    "address": "Trinity, Tea party"
}

### login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "kasummi@gmail.com",
    "password": "kasumigaoka"
}

### Authenticate
GET http://localhost:3000/api/v1/auth/authenticate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OTksIm5hbWUiOiJLYXN1bWkiLCJlbWFpbCI6Imthc3VtbWlAZ21haWwuY29tIiwiaWF0IjoxNzEzNjU3MDcxfQ.9nJqcl5rCl1hWoa0PCR2d4hYvmTC3WKd861jR6vywLc

### register user
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "name": "Mika",
    "email": "mikhailovna@bmail.com",
    "password": "blueArchive",
    "identity_type": "Paspor",
    "identity_number": "2234452",
    "address": "Trinity, Tea party"
}

### index users
GET http://localhost:3000/api/v1/users


### detail users
GET http://localhost:3000/api/v1/users/44


### new bank account to existed user
POST http://localhost:3000/api/v1/accounts
Content-Type: application/json

{
    "users_id": "66",
    "bank_name": "Bank Tabungan Tea Party",
    "bank_account_number": "432244278",
    "balance": 1000000
}

### index account
GET http://localhost:3000/api/v1/accounts


### detail account
GET http://localhost:3000/api/v1/accounts/1


### transfering money
POST http://localhost:3000/api/v1/transactions
Content-Type: application/json

{
    "source_account_id": "1",
    "destination_account_id": "2",
    "amount": 1000
}


### index transaction
GET http://localhost:3000/api/v1/transactions


### detail transaction
GET http://localhost:3000/api/v1/transactions/1
